config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :floor_plans
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/floor_plan.rb
class FloorPlan < ApplicationRecord
  validates_presence_of :display_name
  validates_format_of :blueprint, with: URI.regexp
  validates :project_id, presence: true, numericality: true
  belongs_to :project

  before_destroy :delete_objects_on_s3

  def delete_objects_on_s3
    project_name = self.project.name
    file_key = "#{project_name}/#{URI.decode(self.blueprint.split('/').pop)}"
    display_name = self.display_name
    thumbnail_key = "#{project_name}/#{display_name}_thumb.png"
    large_key = "#{project_name}/#{display_name}_large.png"

    S3_BUCKET.delete_objects({
      delete: {
        objects: [
          {
            key: file_key
          },
          {
            key: thumbnail_key
          },
          {
            key: large_key
          }
        ]
      }
    })
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates_presence_of :name
  has_many :floor_plans, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/floor_plans_controller.rb
class FloorPlansController < ApplicationController
  before_action :set_floor_plan, only: [:show, :edit, :update, :destroy]

  # GET /floor_plans
  # GET /floor_plans.json
  def index
    project = Project.find(params[:project_id])
    @project_name = project.name
    @floor_plans = project.floor_plans
  end

  # GET /floor_plans/1
  # GET /floor_plans/1.json
  def show
    url_fragments = @floor_plan.blueprint.split('/')
    url_fragments.pop
    base_url = "#{url_fragments.join('/')}/#{@floor_plan.display_name}"
    @thumbnail_url = "#{base_url}_thumb.png"
    @large_url = "#{base_url}_large.png"
  end

  # GET /floor_plans/new
  def new
    @floor_plan = FloorPlan.new
  end

  # GET /floor_plans/1/edit
  def edit
  end

  # POST /floor_plans
  # POST /floor_plans.json
  def create
    project = Project.find(params[:project_id].to_i)

    @floor_plans = floor_plan_params[:files].map do |file|
      filename = file.original_filename
      display_name = floor_plan_params[:display_name].presence || filename.split('.')[0]

      # I've considered uploading this in RuMagick as well, but that would not return a public_url
      obj = S3_BUCKET.object("#{project.name}/#{filename}")
      obj.put({acl: "public-read", body: file})
      RuMagick::convert_and_upload(file.path, project.name, display_name)

      existing_plan = FloorPlan.find_by(display_name: display_name)
      if existing_plan.nil?
        attributes = {
          display_name: display_name,
          blueprint: obj.public_url,
          project_id: project.id
        }
        FloorPlan.new(attributes)
      else
        existing_plan.update(blueprint: obj.public_url)
        existing_plan
      end
    end

    respond_to do |format|
      if @floor_plans.map(&:save).all? { |e| e }
        format.html { redirect_to project_floor_plans_path, notice: 'Floor plans were successfully created.' }
        format.json { render :show, status: :created, location: @floor_plans }
      else
        format.html { render :new }
        format.json { render json: @floor_plans.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /floor_plans/1
  # PATCH/PUT /floor_plans/1.json
  def update
    respond_to do |format|
      if @floor_plan.update(floor_plan_params)
        format.html { redirect_to @floor_plan, notice: 'Floor plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @floor_plan }
      else
        format.html { render :edit }
        format.json { render json: @floor_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /floor_plans/1
  # DELETE /floor_plans/1.json
  def destroy
    @floor_plan.destroy
    respond_to do |format|
      format.html { redirect_to project_floor_plans_url(params[:project_id]), notice: 'Floor plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_floor_plan
      @floor_plan = FloorPlan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def floor_plan_params
      params.require(:floor_plan).permit(:display_name, files: [])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/floor_plans_helper.rb
module FloorPlansHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/floor_plans/_form.html.erb
<%= form_for(floor_plan, url: project_floor_plans_path) do |f| %>
  <% if floor_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(floor_plan.errors.count, "error") %> prohibited this floor_plan from being saved:</h2>

      <ul>
      <% floor_plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="display-name" class="field">
    <%= f.label :display_name %>
    <%= f.text_field :display_name %>
  </div>

  <div id="files" class="field">
    <%= f.label :files %>
    <%= f.file_field :files, name: "floor_plan[files][]" %>
  </div>

  <div class="field">
    <%= button_tag "Add more files...", id: "add-more", type: "button" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/floor_plans/edit.html.erb
<h1>Editing Floor Plan</h1>

<%= render 'form', floor_plan: @floor_plan %>

<%= link_to 'Show', project_floor_plan_path %> |
<%= link_to 'Back', project_floor_plans_path %>

app/views/floor_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @project_name %> Floor Plans</h1>

<table>
  <thead>
    <tr>
      <th>Display name</th>
      <th>Blueprint</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @floor_plans.each do |floor_plan| %>
      <tr>
        <td><%= floor_plan.display_name %></td>
        <td><%= link_to floor_plan.blueprint, floor_plan.blueprint %></td>
        <td><%= link_to 'Show', project_floor_plan_path(id: floor_plan.id) %></td>
        <td><%= link_to 'Edit', edit_project_floor_plan_path(floor_plan.project, id: floor_plan.id) %></td>
        <td><%= link_to 'Destroy', project_floor_plan_path(id: floor_plan.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Floor Plan', new_project_floor_plan_path %>

<%= link_to 'Back to Projects', projects_path %>

app/views/floor_plans/new.html.erb
<h1>New Floor Plan</h1>

<%= render 'form', floor_plan: @floor_plan %>

<%= link_to 'Back', project_floor_plans_path %>

app/views/floor_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Display name:</strong>
  <%= @floor_plan.display_name %>
</p>

<%= image_tag @thumbnail_url %>

<p>
  <strong>Blueprint:</strong>
  <%= @floor_plan.blueprint %>
</p>

<p>
  <%= image_tag @large_url %>
</p>

<%= link_to 'Edit', edit_project_floor_plan_path(@floor_plan.project, id: @floor_plan.id) %> |
<%= link_to 'Back', project_floor_plans_path(@floor_plan.project) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FieldwireKeith</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project_floor_plans_path(project) %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>